name: Release Workflow

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository A
        uses: actions/checkout@v2
        with:
          repository: Abikjose/A
          ref: ${{ github.ref }}

      - name: Checkout repository B
        uses: actions/checkout@v2
        with:
          repository: Abikjose/B
          ref: ${{ github.ref }}

      # Add any other necessary steps, such as running unit tests and integration tests.

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
